import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import CarouselBanner from "@/components/CarouselBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>M-Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <CarouselBanner />
        <div className="p-5">
        <h3>Great Deals - 499 only!!</h3>
        <div className="container">
          <div className="row text-center">
            <div className="col-12 col-sm-6 col-lg-3 fs-6 ">
              <Link href="">
                <Image className="my-3" src="/images/image1.jpg" alt="image" height={200} width={200} />
              </Link>
              <p>Women's Heels, Flats...</p>
            </div>
            <div className="col-12 col-sm-6 col-lg-3 fs-6 ">
              <Link href="">
                <Image className="my-3" src="/images/image2.jpg" alt="image" height={200} width={200} />
              </Link>
              <p>Men's Sports Shoes...</p>
            </div>
            <div className="col-12 col-sm-6 col-lg-3 fs-6 ">
              <Link href="">
                <Image className="my-3" src="/images/image4.jpg" alt="image" height={200} width={200} />
              </Link>
              <p>USPA, Levi's, Peter Engl...</p>
            </div>
            <div className="col-12 col-sm-6 col-lg-3 fs-6 ">
              <Link href="">
                <Image className="my-3" src="/images/image5.jpg" alt="image" height={200} width={200} />
              </Link>
              <p>Kids Casual Shoes...</p>
            </div>
          </div>
        </div>
      </div>
      </body>
    </>
  );
}
